### ISSUE TITLE
Error pushing with smart protocol

### ISSUE THREAD

**Issue by jeffa5** [mirage/ocaml-git#387] opened 2020-05-17 19:57 UTC
Hi! When I try to run the code from [this gist](https://gist.github.com/jeffa5/f578763e9c4a42ff435eff68458bf45a) with the [irmin-test](https://github.com/jeffa5/irmin-test) repo at commit 650203dfc04a4e8b441a68a6892f1b8769940c6f I get the following error:
```
Fatal error: exception (Invalid_argument "Sync.push_exn: (`Smart (`Unexpected_char \001))")
```
The scenario is basically:
- clone repo (pull)
- add file and commit
- push back to remote

This actually does push the change to the remote but gives the error and leaves the local repo thinking the remote is still behind.

**Comment by dinosaure** [comment] 2020-09-02 14:01
I need to reproduce the scenario but I believe that #395 fixed the problem.

**Comment by dinosaure** [comment] 2021-12-13 16:26
Lot of things was done since this issue and I'm not sure if it's relevant to keep it. I will close it but feel free to re-open it if you have a problem with the last version of `ocaml-git`.

**Closed by dinosaure** 2021-12-13 16:26 UTC
